version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /userver-auth
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /userver-filemgr
    schedule:
      interval: weekly
